### ISSUE TITLE
Unquoted object keys should support non-ASCII characters

### ISSUE THREAD

**Issue by aseemk** [json5/json5#1]
ES5 allows it. References:
- http://es5.github.com/#x7.6
- https://developer.mozilla.org/en/Core_JavaScript_1.5_Guide/Core_Language_Features#Variables
- http://docstore.mik.ua/orelly/webprog/jscript/ch02_07.htm

Potentially some helpful resources:
- http://stackoverflow.com/questions/147824/javascript-how-to-find-whether-a-particular-string-has-unicode-characters-esp
- http://stackoverflow.com/questions/280712/javascript-unicode

**Comment by 1354092549** [comment]
> Consume Unicode escape sequences and forego testing them against appropriate Unicode classes, willfully violating the ES5 spec.
Maybe this is enough.

**Comment by jordanbtucker** [comment]
Fixed in 35269daf8c8dd257796c1f1dc768bd25175f2c58.
