### ISSUE TITLE
Policy on bumping the version number

### ISSUE THREAD

**Issue by jordanbtucker** [json5/json5#113]
At the time of this writing, this project's version number is 0.4.0 and hasn't been updated since Nov 2014. Let's discuss a policy on when and how version numbers should be updated.

[SemVer](http://semver.org/) is probably the best fit for this project. If we adopt SemVer, we should define when 1.0.0 is ready to be released, since anything with a major version 0 really has no meaning in SemVer.

**Comment by aseemk** [comment]
I'd be okay with just considering the current spec/code 1.0. The main missing feature from the implementation is proper Unicode support, but that's a code issue, and the spec probably matters more than the code (since the code is just a reference implementation).

:+1: to semver in general.

**Comment by jordanbtucker** [comment]
I think I might make this v0.5.0. I'd like to get the following PRs merged before v1.0.0:

- #1: Unicode support
- #84: `--validate` CLI option
- #87: slim down npm payload
- #89: Browserify support
- #94: helpers.js file and fix for `isWord` leaking into public API
- #105: CI improvements including coveralls
- #108: streaming command line and yargs runtime dependency

Once we implement Browserify, we should be able to add in Unicode support.

**Comment by jordanbtucker** [comment]
@aseemk
v0.5.0 is released, but I don't have permission to publish to npm. Thanks.

**Comment by aseemk** [comment]
@jordanbtucker: Your suggestion SGTM. I'll also give you npm publish access! Thanks again for all your great work — it's really helpful to have your hands here.

**Comment by aseemk** [comment]
Looks like I need to know your npm username?

**Comment by aseemk** [comment]
Ah, `jordanbtucker` naturally. =) Added!
