### ISSUE TITLE
Contrast on json5.org

### ISSUE THREAD

**Issue by AlexDaniel** [json5/json5#117]
I cannot find a repo for the website, so I'm opening it here.

Please make the font darker. It is so unreadable that I even went ahead and opened a ticket here.

![screenshot](https://files.progarm.org/2016-04-18-132448_910x418_scrot.png)

↑ Just look at that! Amazing…

I'm not sure what kind of a monitor you should have to read this without having to pick your eyeballs from the floor every 5 seconds.

See also http://contrastrebellion.com/

But seriously, this is not funny at all. What were you thinking?

**Comment by aseemk** [comment]
Thanks for the feedback! You're totally right. This is just one of the built-in GitHub Pages themes.

It looks like the theme has been improved to have better contrast. What do you think of this?

http://orderedlist.com/minimal/

To pick up the changes, I wonder if we just need to re-generate the website.

**Comment by AlexDaniel** [comment]
If we look at the source code we will see that this:
```css
color: #777;
```
Was changed to this:
```css
color: #727272;
```
Which is not that much of an improvement… In fact, it is now **lighter**!!! What the…

However, they've also changed the font itself and current font is much bolder than the previous one. This makes it easier to read (and visually it is perceived as being darker), so that's good. Good but not enough.


By the way, I'm happy to find that I am not alone. See this: https://github.com/orderedlist/minimal/issues/1

In fact, it was fixed here: https://github.com/yegeniy/yegeniy.github.io/commit/79a69bac86fecc0ff89c9ea72124c0322af8f3ce (someone's page).

But there's also this pull request in upstream https://github.com/orderedlist/minimal/pull/2 which changed it to **#666**. However, it was then set back to https://github.com/orderedlist/minimal/commit/3574fcf40f8f3149369ea3d243f23c16196c2b38.

So either fix it yourself or find a new stylesheet. This stylesheet is not that good in other aspects too, so you can safely drop it.

**Comment by AlexDaniel** [comment]
By the way, I've opened a pull request here: https://github.com/orderedlist/minimal/pull/25

If anybody feels with this hilariously light text as uncomfortable as I do, please express your opinion there.

**Comment by aseemk** [comment]
Nice investigation, @AlexDaniel, thanks. I've +1'ed your PR.

I'm happy to either re-generate the content, or if you want to experiment with the stylesheet on the `gh-pages` branch of this repo, happy to take a PR!

**Comment by AlexDaniel** [comment]
It was merged!

**Comment by aseemk** [comment]
Nice! Rebuilt the site, and indeed, contrast looks improved:

http://json5.org/

Thanks again for the feedback!

**Comment by AlexDaniel** [comment]
Actually… this has to be reopened…

See this comment: https://github.com/orderedlist/minimal/issues/1#issuecomment-255735813
