### ISSUE TITLE
automatically "comment" the output json to tell the reader that it was generated.

### ISSUE THREAD

**Issue by bcowgill** [json5/json5#118]
given some/any json5 like so:

```js
{
  anykeywhatsoever: 5 //something
}
```

You could output 'commented' JSON to tell a reader that the file was generated by json5 and should not be edited by hand:

```js
{
  "anykeywhatsoever": "THIS FILE WAS GENERATED BY A http://json5.org TOOL, EDIT THE .json5 SOURCE FILE INSTEAD OF THIS .json FILE",
  "anykeywhatsoever": 5
}
```

The duplicated first key will be superseded by the second key when parsed by a normal JSON parser.

**Comment by jordanbtucker** [comment]
According to [RFC 7159](https://tools.ietf.org/html/rfc7159):

> An object whose names are all unique is interoperable in the sense that all software implementations receiving that object will agree on the name-value mappings. When the names within an object are not unique, the behavior of software that receives such an object is unpredictable. Many implementations report the last name/value pair only. Other implementations report an error or fail to parse the object, and some implementations report all of the name/value pairs, including duplicates.

I don't think JSON5 should always output "unpredictable" JSON. However, if you would like to add that to your JSON5 files manually, you could do something like this:

```js
{
  note: 'THIS FILE WAS GENERATED BY A http://json5.org TOOL,\
EDIT THE .json5 SOURCE FILE INSTEAD OF THIS .json FILE',
  anykeywhatsoever: 5,
}
```

The JSON consumer would need to ignore the "note" property in this case.

**Comment by jordanbtucker** [comment]
This makes me wonder if JSON5 should preserve duplicate keys when compiling to JSON.

**Comment by bcowgill** [comment]
yes, the problem with the note is that some tools generate an error when it doesn't recognize a key.  I wasn't intending it to be a case of always generating the comment key, but perhaps as an option passed in to the json5 tool so users had the choice.

**Comment by jordanbtucker** [comment]
I'm still hesitant about this. Although JSON5 supports duplicate keys, keeping only the last one, outputting duplicate keys feels like promoting them, which is opposite to the stance that [RFC 7159](https://tools.ietf.org/html/rfc7159) takes.

I'd like to see more discussion from others on this topic.
