### ISSUE TITLE
Is there a way to do a roundtrip (load and save)

### ISSUE THREAD

**Issue by DinisCruz** [json5/json5#121]
I have some data stored in json5 files and want to add an editor to it.

So the hard part now is how to save it? 

I can convert json5 into json, the question is how to go from json into json5?

**Comment by aeisenberg** [comment]
json5 has a stringify method. That sounds like what you'd want to use.

**Comment by DinisCruz** [comment]
but does it preserve the previous format?

i'll give it a try and see what it produces

thx

**Comment by aeisenberg** [comment]
As far as I know, formatting is not preserved. json5.stringify accepts the same arguments as JSON.stringify. So, it would reformat the text.

**Comment by DinisCruz** [comment]
ok, so that that will not work for what I'm trying to do (json5 , It's a good project and for config it is a good idea)

Going to close the issue since it the question is answered
