### ISSUE TITLE
CLI tool doesn't support pipes

### ISSUE THREAD

**Issue by vdh** [json5/json5#124]
I tried to combine this with [`jq`](https://github.com/stedolan/jq) today (`npm view react | json5 | jq '."dist-tags"'`) and was very surprised to find that the CLI tool doesn't support pipes. Even the `npm view` I was trying to pipe into it was caught unaware by the lack of a pipe and crashed as a result.

Maybe consider merging #108?

**Comment by jordanbtucker** [comment]
Thanks for the input. #108 needs tests before merging. If you would like to write the tests, it would be greatly appreciated.

I'm going to close this issue since it's in essence a duplicate of #108. Thanks.

**Comment by vdh** [comment]
I guess I'll just use [any-json](https://github.com/laktak/any-json) instead (which ironically, uses json5…)
