### ISSUE TITLE
Beautifier for JSON5

### ISSUE THREAD

**Issue by Kristinita** [json5/json5#127]
In my JSON files are comments and trailing commas. Validators considered non-valid my files and I can not format my files. JSON5 support comments and trailing commas. Are prettifier for JSON5 file format?

Thanks.

**Comment by aseemk** [comment]
Good question. There aren't specifically for JSON5, but since JSON5 is a subset of ES5, you should be able to prettify your JSON5 using any standard JavaScript prettifier.

Let us know (and feel free to re-open) if you run into any issues!
