### ISSUE TITLE
Test cases should be in a separate repository

### ISSUE THREAD

**Issue by ianloic** [json5/json5#130]
Interoperability between different JSON5 libraries would be helped by sharing test cases between implementations. One approach to this would be to have a separate repository for test cases that each implementation could use (via git submodule or similar mechanism).

I took a swipe at this with the test cases here:
  https://github.com/ianloic/json5-parse-test-cases
and a version of the json5 repo using a submodule to bring in those test cases here:
  https://github.com/ianloic/json5

Is this approach appealing? Would other implementors find it useful?

**Comment by jordanbtucker** [comment]
This sounds good for me. Thanks for putting in the work. Please see #131 for continued work and discussion.

**Comment by aseemk** [comment]
I think this is a great idea too! Thanks guys. =)
