### ISSUE TITLE
Possible to skip "unwanted" attributes?

### ISSUE THREAD

**Issue by kayazinc** [json5/json5#133]
For example, we just want to extract the attributes name and age, skipping the address attribute.
```
[
{name: 'clinton', address:'usa', age:'35'},
{name: 'trump', address:'usa', age:'53'}
]
```
Is it possible with JSON5?

**Comment by dessalines** [comment]
JSON is a data format, when you build the data, just leave those out.

**Comment by jordanbtucker** [comment]
If you're parsing the JSON5, you can use the `reviver` argument in `JSON5.parse`. It works the same as [`JSON.parse`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/JSON/parse#Using_the_reviver_parameter).

```js
JSON5.parse(text, function(key, value) {
  if(value['address']) {
    delete value['address'];
    return value;
  }
});
```

If you're stringifying to JSON5, you can use the `replacer` argument in `JSON5.stringify`. It works the same as [`JSON.stringify`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/JSON/stringify#The_replacer_parameter).

There are two ways to use `replacer`, as an array containing the keys you want to stringify,

```js
JSON5.stringify(data, ['name', 'age']);
```

Or as a function that works just like `reviver`.

```js
JSON5.stringify(data, function(key, value) {
  if(value['address']) {
    delete value['address'];
    return value;
  }
});
```

Notice you can use the same function for `reviver` and `replacer` to get the same results.

```js
function addressFilter(key, value) {
  if(value['address']) {
    delete value['address'];
    return value;
  }
}

JSON5.parse(text, addressFilter);

JSON5.stringify(data, addressFilter);
```
