### ISSUE TITLE
Extra spaces in empty arrays when pretty-printing

### ISSUE THREAD

**Issue by dgreensp** [json5/json5#134]
It looks like indentation meant for start of line is being written inline:

```
> console.log(JSON5.stringify({x:[]}, null, 2))
{
  x: [  ]
}
undefined
> console.log(JSON5.stringify({x:{y:[]}}, null, 2))
{
  x: {
    y: [    ]
  }
}
undefined
```

**Comment by jordanbtucker** [comment]
Thanks for the bug report! I just published the fix, so try it out at let us know if you still have any issues.

**Comment by dgreensp** [comment]
Thanks for the ultrafast turn-around!
