### ISSUE TITLE
Formal Grammar

### ISSUE THREAD

**Issue by seagreen** [json5/json5#139]
Has one been written for JSON5?

**Comment by seagreen** [comment]
Also there are some tools to generate railroad diagrams from EBNF or such, so if a formal grammar has been written I'd be happy to take it and make railroad diagrams from it.

**Comment by jordanbtucker** [comment]
[https://github.com/json5/json5-spec]

**Comment by seagreen** [comment]
@jordanbtucker: Thanks! I am extremely new to formal grammars, is there a name for the language that's used to describe JSON5 at the end of that document?

**Comment by jordanbtucker** [comment]
It's not really a formal language, but it's the same [convention](https://es5.github.io/#x5) used in the ES5 spec.

**Comment by seagreen** [comment]
Sorry to get back to this so late!

I am not sure why the ECMAScript people would make up their own convention when formal grammars already exist. For one thing this puts us in a crappy place because we're stuck copying their made up language.

It still might be nice to have a description of JSON5 using an actual formal grammar. We would probably want to use Augmented Backus–Naur because that's what's used in the [JSON spec](https://tools.ietf.org/html/rfc7159#section-2). There are tools to turn Extended Backus-Naur into railroad diagrams, like in this project of mine here: [https://github.com/seagreen/Son](https://github.com/seagreen/Son), we could probably find such a tool for Augmented Backus-Naur as well.

I guess the question is: if we had unlimited volunteer time and could write the spec in any language we wanted, would we go with the ES5 convention or ABNF? I can see advantages for both.

**Comment by jordanbtucker** [comment]
The problem with formal grammars is that, while they're often meant for machine processing, the grammars don't always support the nuances of the languages they parse.

For example, ECMAScript allows [Unicode escape sequences in identifiers](https://es5.github.io/#x7.6) as long as the unescaped value can also be parsed as a valid identifier. In other words:

```js
var a;      // valid identifier
var 0;      // invalid identifier (cannot start with a number)
var \u0061; // valid identifier (\u0061 = 'a')
var \u0030; // invalid identifier (\u0030 = '0')
```

This is not something a lot of, if any, language grammars natively support. Take for example this [ECMAScript parser](https://github.com/bkiers/ecmascript-parser) written with ANTLR. Its [`IdentifierStart`](https://github.com/bkiers/ecmascript-parser/blob/a57e5c1e3912ef8fbb1d51eab93672280477a5b1/src/main/antlr4/nl/bigo/ecmascriptparser/ECMAScript.g4#L1008-L1012) production will parse any Unicode escape sequence regardless of whether or not it's a letter, `$`, or `_`.

I proved this by forking it and adding a [test case](https://github.com/jordanbtucker/ecmascript-parser/blob/master/src/test/java/nl/bigo/ecmascriptparser/ECMAScriptLexerTest.java#L94) that should fail and then building it on Travis CI. All tests [passed](https://travis-ci.org/jordanbtucker/ecmascript-parser/builds/198617352).

Talking specifically about JSON5, its grammar references some ECMAScript 5.1 grammar productions, which would have to be translated to a formal grammar language as well.

You're welcome to make a first go at writing an ABNF for JSON5.

**Comment by seagreen** [comment]
That's really helpful, thanks! I'll close this for now since ABNF won't be a clear win over the current situation. I still might get around to writing one eventually, if I start on it I'll make a new issue to discuss it.

**Comment by nomoon** [comment]
@seagreen https://github.com/antlr/antlr4 might be a good tool for this job. It's well established and has a number of targets for its parser generator, one of which is JavaScript. There's also a sample JSON grammar already defined: https://github.com/antlr/grammars-v4/blob/master/json/JSON.g4

**Comment by d-frey** [comment]
FWIW, I wrote an ABNF for JSON5, see [json5.abnf](https://github.com/json5/json5-spec/blob/2a96dd370a8944003a3d43c740594e76134d10f4/json5.abnf).

As it is an ABNF, the grammar itself might not fully describe the language, additional rules apply (e.g. about valid surrogate pairs in strings, etc.)
