### ISSUE TITLE
Yet another YAML? (JSON5 === YAYAML)

### ISSUE THREAD

**Issue by dreftymac** [json5/json5#140]
## The overview does not mention YAML is isomorphic with JSON

The design philosophy for JSON5 does not mention that YAML syntax supports compatibility with JSON.

Some may want a little more detail on this issue than is given in the overview

## See also

* http://stackoverflow.com/questions/25974485

**Comment by zamicol** [comment]
I don't follow.  That thread states that[ YAML is not a json superset](http://stackoverflow.com/a/26220257/1923095).

**Comment by dreftymac** [comment]
## (TL:DR;) YAML parses JSON just fine, so long as one does not use TAB for indentation

* Boring details below.

## WTF: Is YAML a superset of JSON or not?

YAML does not permit tabs for indentation, that is the single factor that precludes it superset of JSON.

* If a developer wishes to use tabs to indent JSON, then `YAML is not a json superset` holds.
* If a developer avoids using tabs to indent JSON, then `YAML is not a json superset` still holds, but for all practical purposes, YAML and JSON are logically indistinguishable.

Since "tabs vs spaces" is one of those aspects of engineering design that will never be a closed issue, it seems reasonable to leave it at that.

* https://www.youtube.com/watch?v=SsoOG6ZeyUI

**Comment by jordanbtucker** [comment]
@dreftymac This is all interesting information, but what does this have to do with JSON5?

**Comment by dreftymac** [comment]
There is a section already in the documentation and design philosophy which does address why JSON5 is not superfluous, given that YAML already exists.

This is an invitation to readers to further understand the nature of the differences between JSON and YAML; so that they can be well-informed in their choice of JSON5 as an alternative to both classic JSON and YAML.

If there is no need to augment the documentation and design philosophy notes on JSON5, then this issue can be considered complete AFAIC and left only as an historical note.

**Comment by jordanbtucker** [comment]
@dreftymac BTW, I answered that StackOverflow question because the other answerers don't seem to understand the YAML spec.

http://stackoverflow.com/a/42194903/164430
