### ISSUE TITLE
Consider a different tagline for JSON5

### ISSUE THREAD

**Issue by seagreen** [json5/json5#141]
"Modern JSON" isn't very good advertising, or even accurate. 99% of services using JSON are using it for machine to machine communication. JSON5 is clearly not a "Modern JSON" for these use cases, in fact it's worse.

There are lots of things that could go there instead, but what about "Human JSON" or "Humane JSON"? JSON5 is great for what it's meant for and deserves better advertising.

**Comment by aseemk** [comment]
Good suggestion! I like "JSON for humans", inspired by Kenneth Reitz's work (e.g. Requests, HTTPie). How do others feel about that?

(Alternately, the GitHub repo description already also says, "JSON for the ES5 era".)

**Comment by seagreen** [comment]
> "JSON for humans"

I love it.

> "JSON for the ES5 era"

This might be better for specific audiences like frontend devs. I do like that it explains the "5" in "JSON5". I think your previous idea is better for [json5.org](http://json5.org/) though because all kinds of people will be arriving there. Backend devs are unlikely to realize that "JSON for the ES5 era" will be relevant and helpful to them.

**Comment by jordanbtucker** [comment]
I'm on full agreement on this. :100:
