### ISSUE TITLE
.j5on

### ISSUE THREAD

**Issue by techtonik** [json5/json5#144]
Just an idea for a shorter file extension.

**Comment by jordanbtucker** [comment]
Clever :wink:

**Comment by aaronelite93** [comment]
That's a brilliant idea! 5 could stands for S symbol partially in its shape as well as reserving the meaning of version number

**Comment by d-frey** [comment]
Or even just `.j5`?

**Comment by louisbuchbinder** [comment]
What is wrong with ```.json5```?

**Comment by fracz** [comment]
Clever idea, but when it comes to pronunciation, the `json5` is the best.

**Comment by techtonik** [comment]
Okay. `json5` wins with 5 votes.
