### ISSUE TITLE
Can I parse a JSON5 string, modify the object and then stringify the result in standard JSON?

### ISSUE THREAD

**Issue by AleCaste** [json5/json5#146]
I need a JSON5 library to parse strings containing JSON5 data.
After modifying that data, I need to stringify the result in standard JSON-string.

Using JSON5.stringify does not seem good to me since the result is always a JSON5-string (as one would expect). In my case I need the string to be decoded by a server that does not have a JSON5 parser, so that's why I need to produce a standard JSON string.

Is there any argument I can pass to the stringify function to configure the output in such a way?
Thanks a lot!

**Comment by aseemk** [comment]
You can simply use `JSON.stringify` (instead of `JSON5.stringify`) which is built into all JavaScript engines these days.

Hope that helps! Feel free to re-open if not.

**Comment by AleCaste** [comment]
Thanks for the quick response.
Unfortunately the javascript engine I am forced to use does NOT have a JSON.stringify function built in. Along with the JSON5 lib, I could also make use of an additional lib just to generate the standard JSON output... but I feel it should not be necessary. There should be a mechanism in JSON5 customize the output a little bit.
Going through the JSON5 issues I learnt that JSON5.stringify used to generate standard JSON strings years ago. And I also came across another issue talking about the possibility of adding an "options" argument to the stringify function.

**Comment by aseemk** [comment]
Ah, that's surprising and too bad.

`JSON.stringify` is part of the official ES5 standard, which is pretty pervasive these days, so I'm not sure it'd be worth the API surface area for `JSON5.stringify` to re-implement that. We also probably wouldn't do it as robustly or as fast as other libraries, e.g. <https://github.com/bestiejs/json3>.

Good luck!

**Comment by AleCaste** [comment]
No worries. I totally understand your view. I'll simply add the json2 lib to stringify in standard JSON.
It's not that bad after all.
Thanks!
