### ISSUE TITLE
Add a "real" binary type

### ISSUE THREAD

**Issue by d-frey** [json5/json5#148]
Seeing JSON5 more as an extension of JSON rather than a sub-set of ES5, and given that almost every binary representation format of JSON (CBOR, BSON, ...) allows to transfer binary data tagged as such, I wonder if it would make sense to allow "real" binary data in JSON5.

I propose to use the dollar sign ($) to prefix such values, followed by an even number of hexadecimal digits. I would *not* allow them as keys of objects.

Example:

```
{
  string: "deadbeef",
  number: 0xdeadbeef,
  binary: $deadbeef
}
```

A library could either support binary data directly and hence store it as such (like our library would do) or it could store it as a string, in the above example being equivalent to `"\xde\xad\xbe\xef"`.

The reason to choose hex-representation instead of, say, base64 is readability. After all, JSON5 targets humans and we are notoriously bad at reading base64 :)

It would allow JSON5 to increase interoperability with binary protocols. Also, those protocols show that there is a real demand for representing binary data. I also had use-cases where small amounts of binary data had to be part of a config file, so it would make sense to use a special value type for that.

Grammar extension:

```abnf
; new rule for binary values:
binary = %x24 *( 2HEXDIG )

; extend value:
value = null / true / false / number / string / array / object / binary
```

**Comment by jordanbtucker** [comment]
This conflicts with our goal of having JSON5 be a strict subset of ES5 that adds no new data types.
