### ISSUE TITLE
Allow underscore to separate numbers

### ISSUE THREAD

**Issue by d3x0r** [json5/json5#153]
https://github.com/tc39/proposal-numeric-separator

as was mentioned in this thread   https://mail.mozilla.org/pipermail/es-discuss/2017-July/048665.html

easy enough to just 'while in a number, if _ skip and don't collect' 

But since this is on ES5 version this probably doesn't apply.  Just figured I'd see if anyone had interest.

**Comment by jordanbtucker** [comment]
I saw this proposal too. I think it would be a nice addition to [JSONext](https://github.com/jordanbtucker/jsonext), a spiritual successor to JSON5, if it lands in a version of ES.

**Comment by lyrachord** [comment]
May  consider space as well.

pi: 3.14 159 26
movreg: 0x1122 3344 5566 7788
binary: 0 1010 1111 1011 0001

**Comment by KernelDeimos** [comment]
closed as completed? It said it's an invalid syntax character...

**Comment by jordanbtucker** [comment]
Must be a new feature of GitHub. I just normally click the "close" button.

**Comment by KernelDeimos** [comment]
This would've been convenient but I guess it's not in spec. The trouble is migration configuration that was previously done in javascript to json is really difficult when this syntax, regex, multiplication, and such things are used. Although it doesn't seem unreasonable to me to support these. Do you know of any other json-superset js-subset markup language that solves these problems?

**Comment by d3x0r** [comment]
> This would've been convenient but I guess it's not in spec. The trouble is migrating configuration that was previously done in javascript to json is really difficult when this syntax, regex, multiplication, and such things are used. Although it doesn't seem unreasonable to me to support these. Do you know of any other json-superset js-subset markup language that solves these problems?

[json6](https://github.com/d3x0r/json6) and [jsox](https://github.com/d3x0r/jsox)  for underscores, no expressions or regex, but the reviver function passed to `JSON.parse( string,reviver)` can probably resolve those... allowing you run code as it parses the string
