### ISSUE TITLE
Is there a format checker for JSON5 ?

### ISSUE THREAD

**Issue by sachinlala** [json5/json5#155]
For JSON, we have https://jsonlint.com/ and many such tools. I do not find the like for JSON5 which we're needing to use for Joyent ContainerPilot configuration files.

**Comment by jordanbtucker** [comment]
I just released v1.0.0-beta which has a `--validate` CLI option.

```bash
npm install -g json5@beta

json5 --validate my-file.json5
```

It will output an error if the file is invalid or nothing if it is valid. See `json5 --help` for more information.

To validate with the API, you can just use `JSON5.parse` and see if it throws.

---

There is no CLI feature for formatting JSON5, but you can use the API to do it:

```js
const json5 = fs.readFileSync('my-file.json5')
const value = JSON5.parse(json5)
const formattedJSON5 = JSON5.stringify(value, null, 2)
```

---

I'm also considering writing an ESLint plugin for JSON5, and maybe a "Try JSON5 Online" page.

**Comment by sachinlala** [comment]
Thanks @jordanbtucker for the prompt response.

Will be best to have an ESLInk plugin as you suggested.

**Comment by t829702** [comment]
> For JSON, we have https://jsonlint.com/ and many such tools

> I just released v1.0.0-beta which has a `--validate` CLI option.

are there any online version of the JSON5 validator?

the CLIs are good, but an online version of JSON5 tools would be even better

**Comment by Artoria2e5** [comment]
If all you want is to try it online, https://npm.runkit.com/json5 will do. It's not friendly at all, but at least you can parse and dump :/

**Comment by jordanbtucker** [comment]
Here's a quick prototype for trying JSON5 online.

https://jordanbtucker.github.io/try-json5/
