### ISSUE TITLE
Allow JSON5 documents to be surrounded by parentheses

### ISSUE THREAD

**Issue by jordanbtucker** [json5/json5#156]
There are few if any linters and syntax highlighters for JSON5. Treating JSON5 as JavaScript when using a linter or highlighter may work with some documents, but not documents where the root value is an object.

Syntax highlighters have no trouble highlighting the following JSON5 document.

```js
{ a: true }
```

However, as JavaScript, that document is not an object with a single property named `a` and whose value is `true`—it's a [block statement with a labeled statement named `a` and whose body is the expression `true`](http://esprima.org/demo/parse.html?code=%7B%20a%3A%20true%20%7D).

Compare with the following document, which is also a valid JSON5 document and JavaScript object.

```js
{ 'a': true }
```

However, as a JavaScript document, it's a [block statement with a string expression followed by the invalid token `:`](http://esprima.org/demo/parse.html?code=%7B%20'a'%3A%20true%20%7D). And linters and syntax highlighters may call you on it.

Similarly, the following document is valid JavaScript, but not valid JSON5.

```js
{ a: b: true }
```

It's a [block statement with labeled statement named `a` and whose body is another labeled statement named `b` and whose body is the expression `true`](http://esprima.org/demo/parse.html?code=%7B%20a%3A%20b%3A%20true%20%7D).

Surrounding these documents with parentheses forces them to be parsed as expressions rather than block statements.

- `({ a: true})` is an [object](http://esprima.org/demo/parse.html?code=(%7B%20a%3A%20true%20%7D)).
- `({ 'a': true })` is an [equivalent object](http://esprima.org/demo/parse.html?code=(%7B%20'a'%3A%20true%20%7D)).
- `({ a: b: true })` is [invalid](http://esprima.org/demo/parse.html?code=(%7B%20a%3A%20b%3A%20true%20%7D)).

JSON5 could allow optionally surrounding the root value with parentheses to aid linters and syntax highlighters with parsing JSON5 documents.

This of course is not a replacement for a real JSON5 linter or syntax highlighter, which would catch obvious errors like `{ a: function() {} }` and subtle errors like `{ a: - 1 }`.

This is just an idea of mine, and I have no plans to implement it at this point, however I wanted to open it up for discussion to see what everyone thinks.

**Comment by aseemk** [comment]
Not a bad idea! Unobtrusive, and a quick and easy way for people to use existing JS tooling on their JSON5 data.

**Comment by jordanbtucker** [comment]
Easy fix in the grammar too:

```
JSON5Punctuator :: one of
    ( ) { } [ ] : ,

JSON5Text :
    ( JSON5Value )
    JSON5Value
