### ISSUE TITLE
Treat comma as whitespace

### ISSUE THREAD

**Issue by tidde** [json5/json5#157]
Allowing trailing commas in objects and arrays is great, but treating comma as whitespace would be even better.  JSON5 would still be a superset of JSON, someone who likes trailing commas may use them, and anyone who just thinks the commas are meaningless noise in the file is free to leave them out.

I know this comes rather late in the development of the JSON5 specification, but I still think that a discussion of this proposal would be worth having.  If nothing else, it might result in a footnote somewhere in the specification explaining why the silly commas are mandatory in JSON5.

Is it totally out of the question to add something that doesn't come from ES5?  Separators such as commas and semicolons play a certain role in languages with complex expression structures, where they may serve as synchronization points for more helpful parsing error messages, and possibly also for disambiguation.  It might be the case for ES5, but not for JSON5 (addressing the needs for manual editing, readability, and clean diffs).

Just compare:
```
    main: 'lib/json5.js',
    bin: 'lib/cli.js',
    files: ["lib/"],
    dependencies: {},
    devDependencies: {
        gulp: "^3.9.1",
        'gulp-jshint': "^2.0.0",
        jshint: "^2.9.1",
        'jshint-stylish': "^2.1.0",
        mocha: "^2.4.5"
    },
```
with
```
    main: 'lib/json5.js'
    bin: 'lib/cli.js'
    files: ["lib/"]
    dependencies: {}
    devDependencies: {
        gulp: "^3.9.1"
        'gulp-jshint': "^2.0.0"
        jshint: "^2.9.1"
        'jshint-stylish': "^2.1.0"
        mocha: "^2.4.5"
    }
```

**Comment by Peping** [comment]
Isn't JSON5 about enhancing JSON with EcmaScript5 features? This is not valid EcmaScript5.

**Comment by tidde** [comment]
Exactly, that's the question: Is it about enhancing with ES5 features, or is it about making a format for humans (manual editing, readability, and clean diffs)?

For me, the solution was to create a format I call Config Object Notation (with .con as filename extension).  The concrete syntax is even more light weight than the proposal above, while still being trivial to tokenize and parse.  In case someone ends up reading this in search for a format that is more about being for humans than enhancing JSON with ES5 features, these are some of the key features of the format:

- Abstract structure is based on JSON, but with some extensions.  Most notably, documentation comments are supported, see below.  Abstract structure is close enough to JSON to make one way conversion to JSON pretty straight-forward.
- No separator is used between elements in arrays or between key/value pairs in objects.
- The need to quote keys has been further reduced compared to JSON5, almost down to allowing any non-whitespace character in a non-quoted key.
- By requiring the top value to be either an object or an array (which should be fine for any configuration file), the braces around a top level object may be omitted (the to level value must be an object unless the first token is an opening bracket).  Besides dropping the lines with the top level object delimiters, this makes it natural to start all top level key/value pairs in the first column.
- Python style raw strings reduces amount of escape sequences when writing regular expressions.  By being distinct from normal strings in the abstract structure, a tool reading CON and writing back to file will be able to preserve them as raw strings.
- So-called _single line_ comments may only be used to comment out an entire line, and are not part of the abstract structure (a tool reading CON and then writing back to file is not expected to preserve such comments).
- So-called _multi-line_ comments are intended for documentation, and while this is still under development, the idea is that these should only be allowed in certain places, but be part of the abstract structure.  For example, a documentation comment is allowed following (separated only by horizontal space) any non-top value, and is attached to this value in the abstract structure.  Similarly, a documentation comment for the top level value is allowed at the beginning of the file.  Inside arrays, documentation comments may appear among the elements of the array (without being attached to any of the elements) if it is only surrounded by whitespace on the lines it occupies.  Inside objects, documentation comments may appear among the key/value pairs in a similar way.

Example:
```
/* Small example of a Config Object Notation file.
 * (Documentation belonging to to level obejct.)
 */
name: 'CON'
/* Author details (documentation between key/value pairs) */
author-name: 'Henrik'
author-email: 'henrik@service' /* Not working, need to update. (Documentation belonging to value.) */
/* Properties of the Config Object Notation format */
types: [
  /* Plain JSON types */
  { name: 'Boolean' }
  { name: 'Integer' }
  {
    name: 'Float'
    examples: [ 4.2e1 Infinity -Infinity NaN ]
  }
  {
    name: 'String'
    examples: [
      'Hello,'
      "world!"
    ]
  }
  /* Modified JSON types */
  { name: 'Array' } /* May contain documentation comments among elements. */
  { name: 'Object' } /* May contain documentation comments among elements. */
  /* Extensions */
  {
    name: 'RawString'
    examples: [ r'.*\.con' ]
  }
]

```

**Comment by Peping** [comment]
Why don't you go with YAML instead? There's plenty of libraries already supporting it! The README.md in this repository is pretty explicit that JSON5 only intends to add features from EcmaScript5.

**Comment by tidde** [comment]
YAML seems nice in many ways, but I see a few reasons why it would solve my needs:
- Lack of stable implementation in OCaml (which is what I have to use at work), and too complicated to start yet another attempt at implementing it.
- Handling of comments; I really care about the comments, and want to be able to write comment-preserving programs that operate on the "representation graph".
- Presence of aliases also makes transforms more difficult to express; when a line is added to the `bill-to` address, what happens to the `ship-to` address?

I guess one reason there seems to be no mature YAML implementation in OCaml is the complexity of the specification.  JSON is the opposite, and it simplicity really makes it a very useful format.  There are many inspiring ideas in YAML, but if I end up pursuing the CON format, I'll have to strike the right balance so that the burden of implementing the specification becomes more on par with JSON than YAML.

**Comment by ericnewton76** [comment]
Although not precisely the same, I second the notion of whitespace implying commas when necessary.

As much as I dislike CoffeeScript, it handles this concept of not needing commas just fine.  Trailing comma ignoring helps, but its a symptom of a problem where commas arent really even needed.

**Comment by jordanbtucker** [comment]
Hey, everyone. I'm going to close this issue because it is incompatible with the [official specification](https://json5.github.io/json5-spec/). If you would like to continue this discussion, please open an issue on the [official specification repository](https://github.com/json5/json5-spec). Please see the new [issues template](https://github.com/json5/json5/blob/master/.github/issue_template.md) for more information. Thanks.
