### ISSUE TITLE
Numeric keys in an array of objects wrongly throws a syntax error

### ISSUE THREAD

**Issue by bhutaninitin** [json5/json5#161]
Hi,
As per the specs, I think the unquoted numeric keys should not throw an error:

> var x="[{text:{3:{4:5}}}]"
undefined
> JSON5.parse(x)
SyntaxError: Bad identifier as unquoted key at line 1 column 10 of the JSON5 data. Still to read: "3:{4:5}}}]"

> 
Thanks,
Nitin

**Comment by jordanbtucker** [comment]
Thanks for the suggestion. This has been discussed in #55. Please continue this discussion there.
