### ISSUE TITLE
Backticks (as string literal) for multi lined values

### ISSUE THREAD

**Issue by felipenmoura** [json5/json5#162]
I know JSON5 already supports `\` in the end of lines to allow new lines in string values.
Can we have support for using `\`` instead?

```
{
  key: `value
with more than
one line`
}
```

Besides that...even better if we could use variables in there, from the json itself, imagine!

```
{
  name: 'Felipe',
  greet: `Hello there,
it's so nice too see you again, ${name}!`
}
```

**Comment by jordanbtucker** [comment]
Thanks for the suggestion. This has been discussed in #125. Please continue this discussion there.
