### ISSUE TITLE
How to format JSON5 file in vscode?

### ISSUE THREAD

**Issue by muyu66** [json5/json5#166]
VSCode throw a error about not be supported format in vscode. And it's file icon is missing. I think we should provide more support for VSCODE.

**Comment by jordanbtucker** [comment]
I've begun work on a [JSON5 extension for Visual Studio Code](https://github.com/json5/json5-vscode).

**Comment by tonix-tuft** [comment]
I've installed JSON5 syntax plugin on VS Code:

![Screen Shot 2019-04-19 at 10 49 15](https://user-images.githubusercontent.com/10134421/56416357-dfbc8f00-6290-11e9-8411-8ecf6d27b1aa.png)

However, there's no error checking and syntax formatting.

Is this extension still in a work in progress state?

**Comment by jordanbtucker** [comment]
Work on an official VSCode extension probably won't begin until json5@v3 is completed. Any extensions already out there are developed by 3rd parties.

**Comment by tonix-tuft** [comment]
Understood, thanks! Will wait.

**Comment by tonyxiao** [comment]
VScode has a lot of intellisense around `package.json` files. Is there a way to get those behaviors for `package.json5` also?

**Comment by jcrben** [comment]
If all you're doing is using comments, the file extension `.jsonc` seems to work OK

**Comment by samcarey** [comment]
This worked for me, although still not as convenient as an actual vscode formatter: https://github.com/google/json5format
