### ISSUE TITLE
codePointAt doesn't work on IE

### ISSUE THREAD

**Issue by viperfx07** [json5/json5#170]
Object doesn't support property or method 'codePointAt' 

I read about codePointAt and it's apparently not supported on IE
ref: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String/codePointAt

Will json5 version >= 1 onwards not support IE?

tested on 
IE11 - Windows 10
json5 v1.0.1

Thanks

**Comment by jordanbtucker** [comment]
According to Microsoft, Internet Explorer will only receive security updates until the end of its lifecycle, so version 1.0 and later of this JSON5 library will not support Internet Explorer. To use this library with Internet Explorer, please use version 5.0.

**Comment by jordanbtucker** [comment]
I released v2.0.1 today, which includes browser builds in the `dist` directory that target ES5. They should work on IE.
