### ISSUE TITLE
delete require.cache does not work

### ISSUE THREAD

**Issue by alhaag** [json5/json5#174]
I need to make a require on a file already loaded before, however the NodeJS require saves the cached content.

This is resolved by deleting the cache. Ex:
```
var cfg = require(cfgPath)
delete require.cache[require.resolve(cfgPath)]
// change the file...
var cfg = require(cfgPath) // new content is loaded
```

However when using the JSON5 library this does not work. Ex:
```
require('json5/lib/register')
global.JSON5 = require('json5')
var cfg = require(cfgPath)
delete require.cache[require.resolve(cfgPath)]
// change the file...
var cfg = require(cfgPath) // old cache contents are loaded
```

**Comment by jordanbtucker** [comment]
@alhaag I'm not able to reproduce this issue in Node.js v8.11.1. Can you please provide your Node.js version and OS?
