### ISSUE TITLE
Options for preserving comments when editing a JSON5 file by script

### ISSUE THREAD

**Issue by msikma** [json5/json5#177]
I really like the improvements that JSON5 have over regular JSON. Out of personal interest I've been looking into whether I can use this for configuration files that are touched both manually and automatically. An important requirement is that it's possible for everything, e.g. comments and lines split by escaping the newline, to be preserved on save losslessly.

As far as I can tell, this cannot be done with this library. When I run JSON5.parse(), it returns a plain object. What I want would probably require a parser more similar to how XML parsers work, iterating with more complex objects that contain metadata. That way I could iterate past everything I need, add a new node somewhere without disturbing the rest of the data, and write back the file without any of the formatting or manual choices being altered.

Are there any options for this at the moment? Or is anyone working on such a parser? Or better yet, maybe I'm mistaken and there is a way to do this with this library.

**Comment by jordanbtucker** [comment]
A JSON5 reader is a good idea. For version 3 of this library, I'm working on moving the stateful lexer to its own class. This will help facilitate an XML reader style class for JSON5. I don't have an ETA on when version 3 will be out. Version 2 is mostly internal changes and drop for support for Node.js 4.

**Comment by shoogle** [comment]
It should be possible to add comment-like tags like this:

```json5
{
"##": "This is a comment",
"tag": "This is an ordinary string"
}
```

The "comment" will be ignored by any tool that is not using the `##` identifier to mean something else, but it will be preserved on loading and dumping. This was possible even with ordinary JSON.

I personally feel it was right to exclude proper comments from the JSON specification, and that it was a mistake to add them again in JSON5. A better solution would have been to recommend a specific identifier to be used for non-semantic annotations and displayed in a different color by syntax highlighters. This would have given 90% of the benefits of comments for 10% of the effort compared to creating (and using) an XML-style reader.

**Comment by msikma** [comment]
Well, they are part of the spec and as such it would be good to have a parser that can preserve them as best as possible. It's well known that comments can be added to JSON through the method you cite, but even without additional work to this parser this isn't necessary anymore since all comments are ignored when parsing.

I don't mind if someone gets on a soapbox and disagrees with the existence of comments in JSON5, but perhaps this isn't the right place for it.

**Comment by shoogle** [comment]
> I don't mind if someone gets on a soapbox and disagrees with the existence of comments in JSON5, but perhaps this isn't the right place for it.

Of course it is. But I have no intention of starting a holy war so I'll leave it at that.

**Comment by shoogle** [comment]
@msikma, my appologies. My comments were made under the misconception that JSON5 was an officially sanctioned revision to the JSON specification. I see now that is [not the case](https://github.com/json5/json5/issues/175#issuecomment-508958998), so it is of course free to modify JSON's open specification in any way it pleases. But perhaps it would be kind enough to do so in a way that does not imply endorsement by JSON or its creator, who had [good reasons](https://stackoverflow.com/a/33963845) for removing comments from the original specification.

**Comment by jordanbtucker** [comment]
@shoogle Thanks for your recommendations, but @msikma is correct. This isn't the right place for it. If you would like to discuss removal of comments from the JSON5 spec, please open an issue on the [json5-spec repo](https://github.com/json5/json5-spec). This issue that you hijacked is about a parser option for this JSON5 JavaScript library.

**Comment by msikma** [comment]
@jordanbtucker I was wondering, is there any update on v3 of this library? I'm still available to work on the kind of parser I mentioned.

**Comment by fabiospampinato** [comment]
I'm thinking maybe there could be a `json5-ast` package, with the following methods:

- `parse`: generate an AST out of a JSON5 string.
- `stringify`: generate a JSON5 string out of an AST.

So that preserving comments when updating the structure could be implemented this way:

1. Call `AST.parse` to get the AST of the current object/string.
2. Make a patch object, which when merged with the current object will update it the way we want it. Basically if our API looks like this: `.set ( 'key', true )` then we transform that to `{ "key": true }`.
3. Call `AST.parse` on the patch object.
4. Merge the 2 ASTs together, this would merge our patch while preserving comments.
5. Call `AST.stringify` on the merged AST to get string we wanted back.

Does that sound reasonable? Being able to get an AST from existing objects/strings may enable other features as well, and it's a pretty generic solution.

**Comment by IlCallo** [comment]
Hey there, seems like we hit exactly the same need to programmatically update/merge JSON5 (and similar) files.
Our case is about updating VSCode `settings.json` (and potentially other JSON with Comments stuff): https://github.com/quasarframework/quasar/issues/6582

I took a look to TS and Angular custom parsers implementation. The first one is only meant to be used to read stuff, the second one is really too much complex.

**Comment by jordanbtucker** [comment]
Thanks for the suggestions. While I like your ideas, I don't plan on adding any more features to the JSON5 parser at this time. In an effort to keep JSON5 simple, this library will be a reference parser rather than a full-featured, production-ready implementation of a JSON5 parser.

**Comment by msikma** [comment]
That's a shame, but understandable.

I wouldn't mind helping out with a JSON5 AST parser as a separate project, if anybody else here is interested, but I've personally never worked on such a project before. I assume a good way to write one would be to use a library that allows a formal grammar to be specified for parsing and stringifying. Maybe someone else who was interested in this has a better idea of what the options are for such a project.

**Comment by jordanbtucker** [comment]
@msikma See #194

**Comment by jordanbtucker** [comment]
@giacomorebonato Thanks. I've added golden-fleece to the [Wiki](https://github.com/json5/json5/wiki/In-The-Wild).

I plan on releasing JSON5 v3 after April, when Node.js v12 is no longer supported, however it will mostly include performance improvements and refactors.

**Comment by kasperk81** [comment]
so `jq` and `python -m json.tool` used to suck because they choke on comments in json, and now json5 sucks because _despite_ its parser understands json with comments, emitter has no option for it.. so people will keep inventing new tools until a REALLY sane one emerges..
