### ISSUE TITLE
JSON5 for Python?

### ISSUE THREAD

**Issue by DonaldTsang** [json5/json5#184]
Is it possible to have JSON5 libraries for other programming languages e.g. Python?  
I am currently looking at the scripts in https://github.com/CuddleBear92/Hydrus-Presets-and-Scripts that has JSON scripts for use in this Python project https://github.com/hydrusnetwork/hydrus  
The scripts are very convoluted, and there are no proper ways of adding comments to the components of the script.
It would be nice if you could help out.

**Comment by jordanbtucker** [comment]
See this unofficial Python implementation: https://pypi.org/project/json5/

**Comment by DonaldTsang** [comment]
@jordanbtucker might want to reel in https://github.com/dpranke/pyjson5 and https://github.com/Kijewski/pyjson5 into the JSON5 process in https://github.com/json5/json5/issues/190 ?
