### ISSUE TITLE
string with bslash 

### ISSUE THREAD

**Issue by sloanyyc** [json5/json5#191]
json5.loads('{a:"a\/"}')
ValueError: <string>:1 Unexpected "/" at column 7
such as 'http:\/\/domain\/' can't jsonfiy

**Comment by sloanyyc** [comment]
comment 
    def _dqchar__c2_(self):
        self._push('dqchar__c2')
        self._seq([# lambda: self._not(self._bslash_), # this line
                   lambda: self._not(self._dquote_),

temp fix

**Comment by jordanbtucker** [comment]
Thanks for reporting this, however this repository is for the JavaScript JSON5 library. Maybe you're looking for https://github.com/dpranke/pyjson5.

**Comment by sloanyyc** [comment]
Sorry!
