### ISSUE TITLE
Is it possible to write a ReadMe/Wiki on the difference between JSON5 and other neo-JSONs?

### ISSUE THREAD

**Issue by DonaldTsang** [json5/json5#193]
- http://bsonspec.org/
- https://github.com/lightbend/config/blob/master/HOCON.md
- http://amzn.github.io/ion-docs/docs/spec.html
- https://github.com/FasterXML/smile-format-specification
- https://tools.ietf.org/html/rfc7049
- https://msgpack.org/
- http://ubjson.org/

**Comment by jordanbtucker** [comment]
I think the wiki is a better place for this kind of information.

**Comment by DonaldTsang** [comment]
@jordanbtucker ReadMe or Wiki, whichever is more convenient

**Comment by jordanbtucker** [comment]
The wiki is editable by anyone. Please feel free to add this information there.

https://github.com/json5/json5/wiki
