### ISSUE TITLE
pnpm will support package.json5

### ISSUE THREAD

**Issue by zkochan** [json5/json5#197]
I noticed that you have a `package.json5` in the root of the repo (which is autogenerated). [pnpm](https://github.com/pnpm/pnpm) will soon support both `package.json5` and `package.yaml` (related PR https://github.com/pnpm/pnpm/pull/1799).

**Comment by jordanbtucker** [comment]
Nice. I'll have to check `pnmp` out. I did notice once issue in the README:

> When using npm or Yarn for example, if you have 100 projects using the same version of lodash, you will have 100 copies of lodash on disk.

This isn't really true with newer versions of npm and yarn, so it's misleading.

**Comment by zkochan** [comment]
Do you mean Yarn Plug'n'Play and Tink? They are still experimental. The default behavior of npm and Yarn did not change.

**Comment by jordanbtucker** [comment]
Oh, is it saying that all versions of packages are cached system wide? I read it as:

> if you have 100 *dependencies* using the same version of lodash, you will have 100 copies of lodash *in your node_modules folder*.

**Comment by zkochan** [comment]
Correct. Lodash will be in one place on the disk. All projects will use hard links to get lodash (not copies).
