### ISSUE TITLE
Serialize comments

### ISSUE THREAD

**Issue by cbetta** [json5/json5#201]
I've been looking for this across the project but I can't seem to find a definite answer: is it possible to serialize a JSON object and insert comments?

I'm looking for a way to output JSON with comments, but it seems like this project can read these comments but not write them back out. Am I right to think this isn't possible right now?

**Comment by jordanbtucker** [comment]
You're correct. At this time, this library does not serialize comments.

**Comment by cbetta** [comment]
Tnx for clarifying.

**Comment by mbrevda** [comment]
Has anything changed re serializing comments since this issue was last answered?

**Comment by jordanbtucker** [comment]
@mbrevda Nothing has changed that has been released, but I'm working on a Parser class that can output an AST that will have the option to include comments.

**Comment by Valar103769** [comment]
has some else lib support generate comment ?
