### ISSUE TITLE
Short example does not include infinity and NaN

### ISSUE THREAD

**Issue by skoehler** [json5/json5#204]
Please enhance the example in README.md so that it also shows +/-infinity and NaN values. I'd like to know how these are represented and whether it's compatible with python.

**Comment by jordanbtucker** [comment]
`Infinity` and `NaN` are used just like any other numeric value. Just like in ES5, they are case sensitive. You can put a `+` or `-` directly in front of them.

They are both compatible with Python. In Python 2, Infinity and NaN are represented by `float('inf')` and `float('nan')`. In Python 3, they are represented by `math.inf` and `math.nan`.

**Comment by skoehler** [comment]
Sure, I already looked in up in the sources. Just make life easier for lazy people like me. Also, you want to show off all your features in your small example, no?

**Comment by jordanbtucker** [comment]
See https://github.com/json5/json5-spec/issues/2
