### ISSUE TITLE
Can we have a new type of object to support ordered keys?

### ISSUE THREAD

**Issue by contact-ouyang** [json5/json5#207]
I understood that the json object is designed to be unordered,  and json arrays will preserve order. So if I would like to preserve the order , then I should use list instead of object, but it is not convenient if I have an `OrderedDictionary` in the backend.

Now I am using c# for backend, in c#, it has `OrderedDictionary` which will preserve the order. After I marshal the `OrderedDictionary` to json, the order will be lost. When I debug the code, I found the `OrderedDictionary` was totally fine , the only problem was JSON changed the order of the key.

After I google about how to solve the problem, I realized that I am not the only one who asked about how to keep the order of keys in json object. Most backend languages have something similar to `OrderedList`, when they marshal to json , they have the same problems, and all the solutions say that we should use array instead of object.

Can we have a new type of object to keep the order of the keys so that the `OrderedDictionary` can marshal to json with preserved order? Thanks.

**Comment by contact-ouyang** [comment]
Thank you for your reply.  Sorry that I might post the question in the wrong place. I thought JSON5 is improved JSON, I might have misunderstood the purpose of JSON5 library, maybe JSON5 is more about easier configuration purpose, I guess. 

It is great If I have an additional type `Map` in JSON/JSON5 to exchange data, then I don't need to think about transform `OrderedList` to an `Array` (to remember the order) + an `Object` (to remember the key value).

**Comment by i5ik** [comment]
Being able to bring ordered keys to JSON5 would make it easy to check for object equivalence (up to JSON-ifiability).

`J5.stringify(a) === J5.stringify(b)`

Using current JSON you can get false negatives because keys in `a` and `b` may present in different order inside JSON.

It's not an easy issue tho as, how do you define an order?

**Comment by jordanbtucker** [comment]
Reopening this issue to accommodate more discussion.

**Comment by h-h-h-h** [comment]
- It sounds like the JSON5-supporting Python library `anymarkup` would prefer being able to preserve JSON order: https://github.com/bkabrda/anymarkup#notes-on-ordereddict
- And it's conceivable that any software not only reading JSON5 (like [the ones from the wiki](https://github.com/json5/json5/wiki/In-The-Wild#libraries)), but also writing it back (similar to `npm`'s `package.json`), would also prefer to keep user choices like key order as is.
- It's also a common wish/source of confusion: https://www.google.com/search?q=json+object+reordered
