### ISSUE TITLE
Output from "json5 -s 2" should end with newline

### ISSUE THREAD

**Issue by phormio** [json5/json5#213]
Currently, it's mildly annoying to use `json5 -s` from the Unix shell, because the output doesn't end in a newline, which means that the last line is joined with the shell's next prompt.  I think the output of a command such as `echo '{ "a": 1 }' | json5 -s 2` should always end in a newline charcter (or the operating system's equivalent).

**Comment by jordanbtucker** [comment]
Thanks for the suggestions. While I like your ideas, I don't plan on adding any more features to the JSON5 parser at this time. In an effort to keep JSON5 simple, this library will be a reference parser rather than a full-featured, production-ready implementation of a JSON5 parser.
