### ISSUE TITLE
Mongodb support? 

### ISSUE THREAD

**Issue by LifeIsStrange** [json5/json5#214]
There's a Jira ticket but it's visibility isn't public
https://www.google.fr/url?sa=t&source=web&rct=j&url=https://jira.mongodb.org/browse/CSHARP-1317&ved=2ahUKEwiFuLnh-7PmAhVfQkEAHYp7BfkQFjABegQIBxAB&usg=AOvVaw3IpkzFAVt6QC2DCYkE56zd&cshid=1576286244953

**Comment by jordanbtucker** [comment]
Please don't post links to non-public links without giving any information. If you have a feature request, please describe it here.

**Comment by LifeIsStrange** [comment]
@jordanbtucker I am asking if mongodb supports JSON5, I can't find this information.

It would be nice to promote JSON5 to json databases like mongodb but feel free to close the issue.

**Comment by jordanbtucker** [comment]
Can you explain how MongoDB would support JSON5? MongoDB doesn't store its data as text files, so I'm not sure what you're asking for.

**Comment by LifeIsStrange** [comment]
Mongodb store it's data as BSON and I'm not asking for changing the mongodb data format ^^
But as a user of mongodb, I give to the mongodb driver a json and mongodb transform it into BSON. 
What I would like is the ability to pass to the mondogb driver, JSON5 that it would transform into BSON.
So that I could use JSON5 everywhere in my program, without manually casting it into json.

**Comment by jordanbtucker** [comment]
The MongoDB shell already supports a subset of ECMAScript that shares many features with JSON5, including:

- Unquoted keys
- Trailing commas
- Hex numbers
- Several other JSON5 features not supported by JSON

I would argue that the vast majority of JSON5 documents work with the MongoDB shell. Do you have any examples that don't?

**Comment by LifeIsStrange** [comment]
Thanks I wasn't aware of this!

*Do you have any examples that don't?*
No, I'll reopen the issue if I do :)
