### ISSUE TITLE
JSON5 with node tree parsing

### ISSUE THREAD

**Issue by jlyonsmith** [json5/json5#215]
I wanted to make mention of it here of some new functionality that I added to my fork of JSON5 that I thought the maintainers might be interested in.  I wanted to make use of the JSON5 format for a scripting tool where the JSON5 gets loaded, compiled and executed.  Using JSON5 this way it's important to be able to point back to the exact location in the original file where either JSON5 formatting errors occurred, or where other run time problems occurred, i.e. line and offset.   It's also useful to know the type of the JSON5 element, i.e. null, number, string, boolean, array, object.  The current library doesn't support this functionality as the information is lost once the file is read and converted to an actual Javascript object.  This is a deficiency in the Javascript API that JSON5 copied, not the JSON5 library, as the information is all there as the file is being parsed.

So I created a fork where instead of throwing that information away I create a _node tree_,  where each node looks like `{ type, value, line, offset}`  I did this with only a very minor change to the `parse` function, and added an additional `options` argument to optionally enable the feature.  I also created a `simplify` function that can flatten a node tree back into a simple Javascript object.  Finally I made sure the new code has 100% code coverage.

Given that from my testing there is no measurable performance difference caused by this change and no backward compatibility issues caused by it, I wanted to let you know in case you would like to accept a PR with the change into the main library to expand it usefulness.  If not, I totally understand as you may be concerned about strict compatibility.  I'll just keep the fork up-to-date for the time being.

See the fork and `johnls` branch at [jlyonsmith/json5](https://github.com/jlyonsmith/json5/tree/johnls). Also, see [README2.md](https://github.com/jlyonsmith/json5/blob/johnls/README2.md) for more information on the changes.

**Comment by HolgerJeromin** [comment]
Ref https://github.com/tc39/proposal-json-parse-with-source

**Comment by jlyonsmith** [comment]
Thanks @HolgerJeromin .  I had a feeling there would be a TC out there to support something like this. It would be straightforward to refactor my changes to JSON5 and make a PR that supported this proposal if you would accept it into the repo.  Then I could implement the node tree module in much more loosely coupled way.

**Comment by jordanbtucker** [comment]
Thanks for the suggestions. While I like your ideas, I don't plan on adding any more features to the JSON5 parser at this time. In an effort to keep JSON5 simple, this library will be a reference parser rather than a full-featured, production-ready implementation of a JSON5 parser.
