### ISSUE TITLE
Circular references and stable/deterministic stringify

### ISSUE THREAD

**Issue by Eric24** [json5/json5#218]
Are there any plans to add:
1. Support for circular references (really just detection of circular references, so they are marked as such)?
2. Support for stable/deterministic output (where the order of the properties in the stringified output are sorted, i.e. guaranteed to be in the same order)?

These are both common features in a variety of libraries that use the built-in JSON parser/stringifier, but I think they could make sense to build into JSON5 directly.

**Comment by neodon** [comment]
I'll share a couple reasons why I would find item 2 (deterministic output) useful.

I'm using the [JSON Stable Sort](https://marketplace.visualstudio.com/items?itemName=TravisIllig.vscode-json-stable-stringify) extension for VSCode so I can format JSON files to be easier to read and diff.  It works well, except it doesn't support JSON5.

I've also run into situations in the past where I wanted to hash a JSON value to use as a cache key, like for an API query parameter with a JSON value.  In this case the JSON has to be normalized somehow, or better, already a serialized deterministic value.  Doing the latter while supporting JSON5 would be nice.

I'm exploring this repo to see if it's possible for me to understand how this feature might be implemented and whether or not I can do it.  Let me know if you have any more thoughts.

**Comment by jordanbtucker** [comment]
Thanks for the suggestions. While I like your ideas, I don't plan on adding any more features to the JSON5 parser at this time. In an effort to keep JSON5 simple, this library will be a reference parser rather than a full-featured, production-ready implementation of a JSON5 parser.

**Comment by Eric24** [comment]
@jordanbtucker Very well. But am I to understand that JSON5 is in fact only intended to be a reference parser and not intended for use in production? That's a bit of a surprise to hear. If so, do you have any recommendations of libraries that would be suitable for production use?

**Comment by jordanbtucker** [comment]
Well, I'm not trying to say that this library can't be used in production, as it has already been used in production for several years. My point is that this may not be the best library to use moving forward as its features are being frozen indefinitely, and there are other libraries that do more.

For a list of parsers, I recommend visiting [the wiki](https://github.com/json5/json5/wiki/In-The-Wild).
