### ISSUE TITLE
Numeric Separators

### ISSUE THREAD

**Issue by Eric24** [json5/json5#219]
Does the current library support the proposed numeric separator syntax (https://github.com/tc39/proposal-numeric-separator)? If not, it probably should.

**Comment by HolgerJeromin** [comment]
Supported by json6
https://github.com/d3x0r/JSON6/blob/master/README.md

**Comment by Eric24** [comment]
Perfect!

**Comment by jordanbtucker** [comment]
@Eric24 Glad you found an alternative. This will never be implemented since JSON5 is based on ES5 syntax. Also, for future reference, this is the wrong repository to submit this type of request as explained in the issue template. Happy coding!
