### ISSUE TITLE
How to add file dependency of one json5 file to another json5 file?

### ISSUE THREAD

**Issue by ShraddhaDevaiya** [json5/json5#221]
Hello,
Suppose I have one json5  file named **file1.json5** and it is dependent on another **json5** file named **file2.json5**. then how can we add that dependency in **file1.json5** and how can we access those data of **file2.json5** file in **file1.json5** file?  Can you please put some light on it?

**Comment by jordanbtucker** [comment]
Please see the discussion at https://github.com/json5/json5-spec/issues/7
