### ISSUE TITLE
JSON5 for Java?

### ISSUE THREAD

**Issue by brimworks** [json5/json5#230]
I like the JSON5 spec, but was surprised that there aren't many options for a Java implementation. Therefore, I started working on this project last weekend:

https://github.com/brimworks/brimworks.json5.java

Would there be interest in adopting this as a "standard" implementation? Note that I built it with ragel as my lexer generator and I have a unit test that checks that it conforms to json5-test cases.

Some unique features of my library:
- The parser will generate "line precise" error messages (complete with inline strings if the data source supports it).
- The parser emits events so you can choose your own tree builder. The parser also supports obtaining a JSON5Location which is used for the "line precise" errors it will throw on parse errors. This means you can write a tree builder that also validates against a schema and generate nice error messages to indicate the precise location of schema violations. Also, by emitting events one can choose to "stream parse" (aka don't bother to store in memory parts of the document which are not desired). Finally, it also supports obtaining whitespace and comments which can be helpful when performing transforms on documents in a way that preserves whitespace and comments.
- JSON5 numbers are converted into the "smallest possible representation".

Thanks!
-Brian

**Comment by jordanbtucker** [comment]
Thanks for this Java implementation. I don't have plans to add any official parsers at this time, but feel free to add it to [the wiki](https://github.com/json5/json5/wiki/In-The-Wild).

**Comment by brimworks** [comment]
Thanks for the pointer to the wiki.
