### ISSUE TITLE
Add parser implementation for Ruby to Wiki page

### ISSUE THREAD

**Issue by taichi-ishitani** [json5/json5#237]
Hi,

I'm developing a parser implementation for Ruby.
https://github.com/taichi-ishitani/rb_json5

Can I edit the following wiki page and add a link to my implementation?
https://github.com/json5/json5/wiki/In-The-Wild

**Comment by jordanbtucker** [comment]
Yes, the Wiki is available for the public to edit. Thanks for supporting JSON5.

**Comment by taichi-ishitani** [comment]
Thanks for your comment.
I've add my implementation to the Wiki.
