### ISSUE TITLE
Support `--stream` mode in json5 command line tool

### ISSUE THREAD

**Issue by hjfreyer** [json5/json5#238]
If a file contains a sequence of JSON5 values, it'd be great to be able to have a tool that turns it into a sequence of JSON values. For instance:

```
3
{ foo: "bar" }
4 5 [ 'baz' ]
```

Would become:

```
3
{ "foo": "bar" }
4
5
[ "baz" ]
```

I'm defining "stream" to match the behavior of the [Rust JSON stream parser](https://docs.serde.rs/serde_json/struct.StreamDeserializer.html). JSON streams can make for nice and simple RPC channels between processes, and it'd be nice to be able to use JSON5 to write a file with an input sequence.

A workaround is to have the JSON5 file contain an array, and then use `cat myfile.json5 | json5 | jq .[]`.

**Comment by jordanbtucker** [comment]
Thanks for the suggestions. While I like your ideas, I don't plan on adding any more features to the JSON5 parser at this time. In an effort to keep JSON5 simple, this library will be a reference parser rather than a full-featured, production-ready implementation of a JSON5 parser.
