### ISSUE TITLE
Consider listing some other implementations on json5.org

### ISSUE THREAD

**Issue by Artoria2e5** [json5/json5#247]
It appears that JSON5 has become notable enough [to be included in iOS 15.0 beta API](https://twitter.com/lexrus/status/1402462420551946243) -- congrats! A quick look at json5.org seems to only show one implementation in the form of the js library, which is probably not *that* much of a good thing for a general-purpose specification. Maybe there should be a page collecting some other implementations?

**Comment by jordanbtucker** [comment]
Please see https://github.com/json5/json5/wiki/In-The-Wild

**Comment by liqiongfan** [comment]
Zua may be what you want.
https://github.com/iqiongfan/Zua

**Comment by jordanbtucker** [comment]
Fixed by #291
