### ISSUE TITLE
Will there be lib parser written in c++ in the future?

### ISSUE THREAD

**Issue by esraels** [json5/json5#250]
Will there be lib parser written in c++ in the future?

**Comment by jordanbtucker** [comment]
Maybe, but I won't likely be the one to write it. If someone would like to contribute to that, it would be appreciated.

**Comment by liqiongfan** [comment]
Zua may be what you want.
https://github.com/iqiongfan/Zua

**Comment by jordanbtucker** [comment]
@liqiongfan Thanks for the info. Feel free to add that to the [wiki](https://github.com/json5/json5/wiki/In-The-Wild).

There's also [json5_parser](https://github.com/Caltech-IPAC/json5_parser) listed there too.
