### ISSUE TITLE
`stringify` should have an options for a newline at the end

### ISSUE THREAD

**Issue by pvinis** [json5/json5#260]
I do this somewhere in my code, `fs.writeFileSync("./metaflags.json5", JSON5.stringify(metaflags, undefined, 2))`, and this makes a file with no eof newline. Is there an easy way to add this from the json5 lib or is my only option to `+ '\n'` or something?

**Comment by zamicol** [comment]
As far as behavior is concerned, I would expect a newline character to be specified by your application (and not stringify).  

It's easier to add a newline than to remove an unneeded new line.

**Comment by jordanbtucker** [comment]
Thanks for the suggestion. This is not currently a feature of JSON5. I'm considering this library "feature complete" and will only be publishing security fixes.

You may want to checkout alternative JSON5 libraries if you need other features.

https://github.com/json5/json5/wiki/In-The-Wild
