### ISSUE TITLE
New `stringify` configurability options?

### ISSUE THREAD

**Issue by adamhamlin** [json5/json5#265]
This is just a couple suggestions for new configurable options for `JSON5.stringify(...)`:
- Configure inclusion of trailing comma
- Configure inclusion of whitespace "padding" for single line output. For example, allow to output `{ key1: 'value1', key2: 'value2' }` instead of `{key1:'value1',key2:'value2'}`.

Thanks for your consideration!

**Comment by jordanbtucker** [comment]
Thanks for this suggestion. In order to keep this reference implementation simple, we're going to keep the configuration options to a minimum for now. These options might be available in a more complex implementation.
