### ISSUE TITLE
Security Vulnerability issue

### ISSUE THREAD

**Issue by chirag-rakholiya** [json5/json5#270]
As we are using JSON5 , we have analyze that there is one of dependency of the json5 named as "minimist@1.2.5" having security vulnerability issue . the latest version of "json5 @2.2.1" and "json5@2.2.0" used the same dependency which causing the security vulnerability issue.

for more information :-  https://snyk.io/test/npm/minimist/1.2.5

is there any way to resolve this issue ?

**Comment by jordanbtucker** [comment]
Thanks for asking about this. json5 has zero production dependencies. This was fixed in #267 and released in [v2.2.1](https://github.com/json5/json5/releases/tag/v2.2.1). If json5 is being flagged as having minimist as a dependency, then it is a dev dependency only.
