### ISSUE TITLE
core-js@<3.4 has been deprecated

### ISSUE THREAD

**Issue by tomoat** [json5/json5#271]
This version has been deprecated
Author message:

core-js@<3.4 is no longer maintained and not recommended for usage due to the number of issues. Because of the V8 engine whims, feature detection in old core-js versions could cause a slowdown up to 100x even if nothing is polyfilled. Please, upgrade your dependencies to the actual version of core-js.

**Comment by jordanbtucker** [comment]
Thanks for the suggestion, but json5 has no production dependencies, so this is only an issue with development.
