### ISSUE TITLE
Rename `master` branch to `main`

### ISSUE THREAD

**Issue by aseemk** [json5/json5#277]
I just noticed that our main branch is still named `master`. The broader git/GitHub/open-source communities changed convention to use the name `main` instead over the last couple of years. E.g.:

* https://github.com/github/renaming
* https://about.gitlab.com/blog/2021/03/10/new-git-default-branch-name/ (links to other articles)
* https://lore.kernel.org/git/pull.656.v4.git.1593009996.gitgitgadget@gmail.com/ (links to other articles)

Fortunately, GitHub did great work to make renaming `master` to `main` much easier (see first link above), so this is hopefully trivial. But I wanted to quickly open this issue before just executing the rename: any consideration or impact I'm missing? cc @jordanbtucker in particular.

Screenshot from the rename dialog here:

https://github.com/json5/json5/settings/branches

<img width="463" alt="Screen Shot 2022-06-13 at 6 40 42 AM" src="https://user-images.githubusercontent.com/537838/173368898-7454238c-9d90-44f9-9b4c-026ab95b54be.png">

**Comment by jordanbtucker** [comment]
Done! 🎉
