### ISSUE TITLE
Support Template Literals using backticks?

### ISSUE THREAD

**Issue by loreto** [json5/json5#302]
Hi,

Would JSON5 be open to adding support for Javascript template literals using backticks as per the EcmaScript 6 spec:
+ https://262.ecma-international.org/6.0/#sec-template-literals
+ https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Template_literals

We currently have our own library that supports JSON with template literals here: https://github.com/jetpack-io/hujson

But to be honest, instead of creating one more JSON-based format, I'd prefer it if this was just part of JSON5.

**Comment by jordanbtucker** [comment]
Thanks for the suggestion. Please see #162.
