### ISSUE TITLE
Online JSON5 Editor(Formatter) is misleading?

### ISSUE THREAD

**Issue by polarathene** [json5/json5#337]
The project links to [this online editor/playground](https://json-5.com/), which lets the user experiment with JSON5 and see it converted to JSON.

It appears to have several bugs related to the number support mistakenly being handled as strings? Additionally the `lineBreaks` example errors.

---

The README has the following [kitchen sink](https://github.com/json5/json5#example) example:

```json5
{
  // comments
  unquoted: 'and you can quote me on that',
  singleQuotes: 'I can use "double quotes" here',
  lineBreaks: "Look, Mom! \
No \\n's!",
  hexadecimal: 0xdecaf,
  leadingDecimalPoint: .8675309, andTrailing: 8675309.,
  positiveSign: +1,
  trailingComma: 'in objects', andIn: ['arrays',],
  "backwardsCompatible": "with JSON",
}
```

Results in the error:

```
Error: Bad string at line 6,0 >>>No \\n's!",
  hexade ...
```

When the multi-line escaped `lineBreaks` example is omitted, it serializes into the following JSON:

```json
{
  "unquoted": "and you can quote me on that",
  "singleQuotes": "I can use \"double quotes\" here",
  "hexadecimal": "0xdecaf,",
  "leadingDecimalPoint": ".8675309, andTrailing: 8675309.,",
  "positiveSign": "+1,",
  "trailingComma": "in objects",
  "andIn": [
    "arrays"
  ],
  "backwardsCompatible": "with JSON"
}
```

- `hexadecimal` was treated as a string instead of a number.
- `leadingDecimalPoint` also becomes a string without a leading `0`.
- Due to the string treatment of `leadingDecimalPoint`, the `andTrailing` entry was absorbed as part of the string.
- `positiveSign` is a string instead of `1` number.

**Comment by jordanbtucker** [comment]
Thanks for reporting. Can you please tell me where this project links to that online editor?

**Comment by polarathene** [comment]
Apologies, I've got quite a few tabs open for comparing JSON5 implementations and mixed that editor link to this project.

It appears to have been one of the front page results for a `json5` search. I mixed the `json-5.com` address with the `json5.org` that this repo links. Sorry about that 😓
