### ISSUE TITLE
better support for text blocks

### ISSUE THREAD

**Issue by RichMorin** [json5/json5#52]
I would like JSON5 to have better support for text blocks. Currently, JSON's only way of encoding blocks of text is to enclose them in double quotes.  So, any double quotes in the text must be escaped.  Also, any embedded newlines are retained.

YAML (yaml.org) allows blocks of arbitrary text, the only restriction being that it must be indented past the key.  It also supports two forms of text blocks: ones which begin with a "|" retain all white space (including newlines and tabs), as is; ones which begin with a ">" convert all sequences of white space to single spaces.

Python (python.org) uses a sequence of three double quotes (""") to begin and end a text block.  This pretty much resolves the problem of embedded quotes, as this sequence is very unlikely to appear in a normal text block.

Variations on this approach (eg, ""|...|"", ""<...>"") might allow JSON5 to handle white space in the ways that YAML does.

**Comment by benatkin** [comment]
I think this is enough reason to iterate on the format, but likely enough of a breaking change that it should be renamed.

**Comment by benatkin** [comment]
Oh, I see the json6 label, and found a project called [json6](https://github.com/d3x0r/json6). Thanks!
