### ISSUE TITLE
Support for numeric literals as property names

### ISSUE THREAD

**Issue by jordanbtucker** [json5/json5#55]
ES5 supports _numeric literals_ as _property names_ in _object literals_. [[ES5 §11.1.5](http://es5.github.io/#x11.1.5)]

This allows productions like:

``` js
{    1 : 'int',
    .2 : 'float',
    3. : 'trailing dec',
  4e-2 : 'exp',
  0x50 : 'hex' }
```

All property names are normalized to strings. So the above will result in:

``` js
{    '1' : 'int',
     '3' : 'trailing dec',
    '80' : 'hex',
   '0.2' : 'float',
  '0.04' : 'exp' }
```

Note that the definition of _numeric literal_ precludes signed numbers and special IEEE 745 values, so the following productions are either errors or not treated as numeric values.

``` js
{        -1 : 'neg (error)',
         +1 : 'pos (error)',
   Infinity : 'inf (valid but parsed as identifier)',
  -Infinity : 'neg inf (error)',
        NaN : 'not a num (valid but parsed as identifier)' }
```

Are there plans to support the same syntax that ES5 does? I don't see floating points used as property names very often, but I can see decimal and hexadecimal integers being useful.

**Comment by kylpo** [comment]
Hey, just wanted to add that I would definitely appreciate numeric literals as property names. e.g. `JSON5.parse("{0.5:true}")` parsing without error. For now, I'm just regex to replace my strings before sending it to json5, but I'd love to take out that step!

Thanks for your work on json5!

**Comment by aseemk** [comment]
@kylpo: Thanks for your feedback! Can you share your use case a bit?

**Comment by kylpo** [comment]
Absolutely! My use case is very specific: I am building an animation component that accepts a `keyframes` object or string. For my convenience and skim-ability, I often prefer to use a string, like:

```jsx
<Animate
  animation={`{
    0: {
      opacity: 0.5,
    },
    0.5: {
      opacity: 0,
    },
    1: {
      opacity: 1,
    }
  }`}
  duration={500}
>
```

`Animate` takes this string and converts it to an object using json5. For number-type consistency within this `animation` string, I do not want to force devs to add quotes around the keys, it "feels" more jarring:

```jsx
<Animate
  animation={`{
    '0': {
      opacity: 0.5,
    },
    '0.5': {
      opacity: 0,
    },
    '1': {
      opacity: 1,
    }
  }`}
  duration={500}
>
```

Thanks for your quick response!

**Comment by jordanbtucker** [comment]
I wrote the code for this in the [numeric-keys](https://github.com/jordanbtucker/json5/tree/numeric-keys) branch of my fork. It wasn't a difficult change.

I'm not advocating that we implement this, I just wanted to see how much work it would be. Now the code is already written if we want to.

Still not sure why a couple unrelated Travis CI tests are [failing](https://travis-ci.org/jordanbtucker/json5/jobs/198648017) when they pass on my machine.
