### ISSUE TITLE
Write a well-defined grammar

### ISSUE THREAD

**Issue by jordanbtucker** [json5/json5#61]
I think JSON5 would benefit from a well-defined grammar like [ECMAScript](http://es5.github.io/#A.1) and [JSON](http://es5.github.io/#x15.12.1) have. I wrote a [prototype](https://gist.github.com/jordanbtucker/ddfcc0f049883bd3786d). The [README](https://gist.github.com/jordanbtucker/ddfcc0f049883bd3786d#file-readme-md) is at the bottom.

**Comment by jordanbtucker** [comment]
We now have an [official spec](https://github.com/jordanbtucker/json5-spec) in draft status.

Ideally, discussions regarding the future of JSON5 will be discussed in the json5-spec repo, while discussions regarding the JavaScript reference implementation will still be discussed in this repo.

I'd like to separate the _goal_ of JSON5 from the different _implementations_.

Let me know what you think.

**Comment by aseemk** [comment]
Nice @jordanbtucker.

Question: should we (finally) just create a `json5` organization and move these repos there?

**Comment by jordanbtucker** [comment]
@aseemk That sounds good. I've got a partial C# implementation and another one for Go, but I haven't uploaded them yet.

**Comment by aseemk** [comment]
Thanks @jordanbtucker on creating the org! Happy to move this repo there. Should we keep the name simply `json5`, or change to `json5-js`?

**Comment by jordanbtucker** [comment]
I'm thinking `json5` for now.

**Comment by aseemk** [comment]
Woohoo! Done. =)

https://github.com/json5/json5

**Comment by jordanbtucker** [comment]
@aseemk Awesome. Thanks.

BTW, did you see this [controversial issue](https://github.com/json5/json5-spec/issues/2) about removing support for `Infinity` and `NaN` on the json5-spec repo?
