### ISSUE TITLE
Update Grammar: JSON5 does not use ECMAScript line terminators

### ISSUE THREAD

**Issue by jordanbtucker** [json5/json5#70]
As specified in the first paragraph describing [`JSON.parse`](http://es5.github.io/#x15.12.2):

> JSON ... allows Unicode code points U+2028 and U+2029 to directly appear in _JSONString_ literals without using an escape sequence.

ES5 does not allow those characters in strings unescaped, since it includes those characters in its [_LineTerminator_](http://es5.github.io/#x7.3) production.

In order to be backward compatible with JSON, JSON5 must also support those characters in strings and therefore cannot reference any of ES5's productions that recursively reference _LineTerminator_ or [_LineTerminatorSequence_](http://es5.github.io/#x7.3), namely [_Comment_](http://es5.github.io/#x7.4) and [_StringLiteral_](http://es5.github.io/#x7.8.4). At least not without caveats.

For this reason, I have updated the [Grammar](https://github.com/aseemk/json5/wiki/The-JSON5-Grammar) to indicate that the _LineTerminator_ and _LineTerminatorSequence_ productions should be substituted with alternative versions defined therein.

The alternative was to recursively redefine the very long _Comment_ and _StringLiteral_ productions as JSON5 versions.

No changes to code are required.

**Comment by jordanbtucker** [comment]
@aseemk I'm not so sure that ES5 should win over JSON in this instance.

The JSONP issue can be fixed by JSONP implementations, and since JSON is an official standard and JSONP is not, the onus is on JSONP implementations to escape `\u2028` and `\u2029` in strings.

It may be true that not many people would be using those characters in hand-written JSON5, but what about the cases where existing JSON files are parsed as JSON5? They'll fail if they contain those characters.

I think it's more important for JSON5 to be backward compatible with JSON in this case. In other words, it's more important that JSON5 can parse JSON than that ES5 can parse JSON5. `eval` is strongly discouranged, so the only other time JSON5 would be parsed as ES5 is in JSON5P (working title) implementations and when the user copies and pastes JSON5 directly into their JavaScript.

This only applies to parsing strings, however. Whether we allow those characters in comments is up for discussion. I'm leaning toward keeping the ES5 standard and rejecting them.

**Comment by aseemk** [comment]
Great points, @jordanbtucker.

Funny enough, the two unsafe chars just hit us at @FiftyThree: we just had site-wide downtime this morning from user input that had them.

https://medium.com/joys-of-javascript/json-js-42a28471221d

Our context was that we take server-side JSON data and render it to client-side JS (to bootstrap client-side functionality). Bug filed with our rendering lib:

https://github.com/malgorithms/toffee/issues/34

To be clear, this was programmatic JSON, not handwritten JSON5. The characters came from user input, probably copy-pasted somehow (as it didn't look malicious).

I guess this issue boils down to these questions for me:

- How often does (legitimate) JSON have these two characters?
- How often are people parsing JSON5 as JS? (Whether through JSONP, `eval`, or rendering.)
- ==> How often are people parsing JSON with these legitimate characters, with JSON5, as JS?

**Comment by jordanbtucker** [comment]
What if we parse `\u2028` and `\u2029` (perhaps with a warning) but never output those characters unescaped?

I had that idea last time I posted, but I discarded it because I didn't like having a parser that does match the spec. But after your comments, I started thinking about the difference between HTML and XML parsers. Does JSON5 need to have draconian error handling like XML, or can we take a page from HTML's tag soup handling?

In this case:

- `\u2028` and `\u2029` are not valid in strings in JSON5.
- JSON5 will parse `\u2028` and `\u2029` anyway (perhaps with a warning).
- JSON5 will escape those characters when stringified.

If you have a JSON5 file with those characters, and the contents of that file are in a variable named `file`, you can call `JSON5.stringify(JSON5.parse(file))` and you'll get back valid ES5 that you can inject into scripts.

And you can do the same thing if `file` is regular JSON, too.

**Comment by jordanbtucker** [comment]
Fixed in 35269daf8c8dd257796c1f1dc768bd25175f2c58
