### ISSUE TITLE
a big fat discussion about octal literals

### ISSUE THREAD

**Issue by rlidwka** [json5/json5#76]
There are two good ways to deal with them:

1. ES3 way, or treat them as octals, which means:
- `\1` -> `\u0001`
- `\8` -> parse error (?)
- `020` -> `16`
- `080` -> parse error (?)
- `0o20` -> parse error

2. ES8 way, or treat them as decimals, which means:
- `\1` -> `1`
- `\8` -> `8`
- `020` -> `20`
- `080` -> `80`
- `0o20` -> `16`

---

About strict mode:

Strict mode is not a complete solution, it is just an intermediate mode between es3 code and future ecmascript versions.

And frankly speaking, it failed. The idea was to have a simpler JS parser, but it ended up all JS engines having 2 parsers, and now there are discussions in es-discuss about how can we get "just one JavaScript" back.

But nevermind that. My point is: comparison with strict mode doesn't make any sense, we either look for b/w compatibility or look into the future, and strict mode is just an intermediate one.

---

What it is and how it is used:

Octal, or base-8 literals, are heavily used in unix programming. Most famous example are file permissions (which are octal based, i.e. you could read `0755` as `-rwxr-xr-x`):

``` js
mode = 0777 & (~process.umask());
```

(source: [substack/node-mkdirp](https://github.com/substack/node-mkdirp/blob/b98bedf92798ed73c87413eaf413d01dbe094a09/index.js#L19))

Javascript got them from C or something like that, they are rarely used in web. But when node.js came in, octal numbers started to be used a lot (see Brendan's [post](https://mail.mozilla.org/pipermail/es-discuss/2012-January/019434.html) in es-discuss 2 years ago).

Another use-case is ANSI escape sequences, in unix manuals ESC is usually written as `\033`:

``` js
console.log('  \033[90mrendered \033[36m%s\033[0m', path);
```

(source: [visionmedia/jade](https://github.com/visionmedia/jade/blob/edf713ab28c309fb0b2c367a4bbe4fc0cbccccc0/bin/jade.js#L181))

---

Why it was considered a bad thing:

Developers who are unfamiliar with language could mistake them for decimal numbers and use them for padding.

Unfortunately, I can't find a single example of such an error right now.

But there is a notable example in [es-discuss](https://mail.mozilla.org/pipermail/es-discuss/2014-August/038596.html) where people use octals, but probably don't even know they do:

```
new Date(2014, 08, 05)
new Date(2014, 10, 12)
```

Here `08` is a decimal, but `05` is octal. But it has no real effect, because single digit numbers are the same in any base.

---

How ES7+ is going to solve this:

Future javascript versions will allow `0o777` syntax as a direct replacement for `0777`. You can test it right now in Firefox console. Unfortunately, I don't know any replacements for inline octals in strings.

Octals aren't deprecated because people don't like them. They are deprecated, because there is a talk about replacing them with decimal numbers, so:

```
ES3: `0123` -> 83
ES6: `0123` -> parse error
ES8: `0123` -> 123
```

I use "ES8" loosely, but the idea stays the same.

---

Now the main question:

Do we stick with legacy ES3 semantics, or follow bleeding edge of ES standards? There is no legacy JSON5 code to worry about, so either choice looks like a valid one.

**Comment by jordanbtucker** [comment]
Hey, everyone. I'm going to close this issue because it is incompatible with the [official specification](https://json5.github.io/json5-spec/). If you would like to continue this discussion, please open an issue on the [official specification repository](https://github.com/json5/json5-spec). Please see the new [issues template](https://github.com/json5/json5/blob/master/.github/issue_template.md) for more information. Thanks.
